extra_javascript:
- javascripts/config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
-   pymdownx.arithmatex:
        generic: true
-   pymdownx.highlight:
        use_pygments: true
- codehilite
-   toc:
        permalink: true
nav:
-   Algorithms:
        Sort:
        -   Merge sort: algorithms/sort/merge_sort
        -   Insertion sort: algorithms/sort/insertion_sort
        -   Selection sort: algorithms/sort/selection_sort
        -   A:
            -   A: algorithms/sort/a/a
site_name: Algorithm
theme:
    name: material
