extra_javascript:
- javascripts/config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- js/expand.js
markdown_extensions:
-   pymdownx.arithmatex:
        generic: true
-   pymdownx.highlight:
        use_pygments: true
- codehilite
-   toc:
        permalink: true
nav:
-   Notebooks:
    -   Raw: raw.md
-   Algorithms:
        Sort:
        -   Merge sort: algorithms/sort/merge_sort.md
        -   Insertion sort: algorithms/sort/insertion_sort.md
        -   Selection sort: algorithms/sort/selection_sort.md
-   Problems:
    -   Two sums: problems/two_sums.md
    -   Two sums ii: problems/two_sums II.md
    -   Add two numbers: problems/add_two_numbers.md
    -   Combine sorted array: problems/combine_sorted_array.md
site_name: Algorithm
theme:
    features:
    - instant
    - navigation.expand
    name: material
